package com.opsbytemitope.entity;

/**
 * Types of activity events generated by the system.
 */
public enum EventType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_ASSIGNED,
    TASK_DELETED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_STATUS_CHANGED,
    PROJECT_DELETED,
    USER_JOINED,
    COMMENT_ADDED
}
